Repository SRM-IST-KTR/githubsrmv2, pull requests merged in 2024-11, with the labels that each got.

#123 Sh/feat/dynamic sponsors
  components/Home/Sponsors.jsx
  pages/api/v1/sponsers/index.js
  public/sitemap-0.xml
  utils/models/sponser.model.js
Labels: enhancement

#126 Solved Issue86
  pages/events/index.js
Labels: Fixed

#122 removed the recruitment section from the website along with the code elements and images
  components/Recruitment/CountdownTimer.jsx
  components/Recruitment/DomainCard.jsx
  components/Recruitment/FormSub.jsx
  components/Recruitment/Hero.jsx
  components/Recruitment/Submission/EmailLogin.jsx
  components/Recruitment/Submission/ProfileCard.jsx
  components/Recruitment/Submission/TaskCard.jsx
  components/Recruitment/Submission/TechForm.jsx
  components/Recruitment/Submission/TimeLine.jsx
  components/Shared/Navbar/Navbar.jsx
  pages/recruitment/dashboard.js
  pages/recruitment/index.js
  public/RecruitmentPoster.png
  public/recruitmentpos.jpg
  public/sitemap-0.xml
Labels: enhancement

#120 Update Faq.jsx
  components/Contact/Faq.jsx
Labels: UI Fixes
