Repository SRM-IST-KTR/githubsrmv2, pull requests merged in 2024-10, with the labels that each got.

#74 For corp, change "Submit task" to "View task"
  pages/recruitment/dashboard.js
Labels: enhancement

#77 Dj/feat/teamUpdate
  components/Team/profileCard.jsx
  pages/team.js
Labels: enhancement

#78 updated Teams page
  components/Team/profileCard.jsx
  pages/team.js
Labels: enhancement

#79 uj/feat/spacing
  components/Shared/Footer/Footer.jsx
  components/Team/Hero.jsx
  pages/team.js
Labels: Fixed

#80 Refactor page title, metadata, and sitemap generation
  next-sitemap.config.js
  package.json
  pages/_app.js
  pages/about.js
  pages/contact.js
  pages/events/index.js
  pages/team.js
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  yarn.lock
Labels: enhancement

#81 Improved SEO
  components/Shared/Footer/Footer.jsx
  components/Team/Hero.jsx
  next-sitemap.config.js
  package.json
  pages/_app.js
  pages/about.js
  pages/contact.js
  pages/events/index.js
  pages/team.js
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  yarn.lock
Labels: enhancement

#76 Fix code scanning alert no. 2: Database query built from user-controlled sources
  pages/api/v1/events/register/index.js
Labels: enhancement

#95 Sponsor's component
  README.md
  components/Home/Sponsors.jsx
  pages/api/v1/events/register/index.js
  pages/index.js
  public/sitemap-0.xml
Labels: enhancement

#102 uj/update/readme
  README.md
Labels: documentation

#106 uj/docs/standards
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  LICENSE
Labels: documentation

#109 uj/analytics
  package.json
  pages/_app.js
  pages/about.js
  pages/contact.js
  pages/index.js
  pages/team.js
  public/sitemap-0.xml
  yarn.lock
Labels: enhancement, dependencies

#98 uj/update/gallery
  components/Home/Gallery.jsx
Labels: UI Fixes

#118 Update README.md
  README.md
Labels: documentation

#111 sy/update/footer
  components/Contact/Faq.jsx
  components/Shared/Footer/Footer.jsx
  package.json
  public/sitemap-0.xml
Labels: UI Fixes

#117 Update ContactForm.jsx
  components/Contact/ContactForm.jsx
Labels: UI Fixes

#113 uj/update/uichanges
  README.md
  components/Contact/ContactForm.jsx
  components/Contact/Faq.jsx
  components/Home/About.jsx
  components/Home/Gallery.jsx
  components/Home/Hero.jsx
  components/Shared/Footer/Footer.jsx
  package.json
  public/sitemap-0.xml
Labels: UI Fixes
